x

diff --git a/cleandisk b/cleandisk
--- a/cleandisk
+++ b/cleandisk
@@ -8,6 +8,7 @@ dir=
 minfree=0
 dryrun=
 mtimearg=
+lockdir=
 findargs=()
 
 while [ $# != 0 ]; do
@@ -35,6 +36,10 @@ while [ $# != 0 ]; do
     mtimearg="-mtime ${2:?}"
     shift 2
     ;;
+    --lockdir)
+    lockdir=x
+    shift
+    ;;
     --clobber)
     rmfilecmd=clobber
     shift
@@ -53,6 +58,12 @@ while [ $# != 0 ]; do
     ;;
     esac
 done
+
+if [ "$lockdir" ]; then
+    exec 5<"${dir:?}"
+    echo "trying to lock directory"
+    flock -w 60 5 && echo "directory locked" || >&2 echo "directory lock failed"
+fi
 
 {
 read s &&
@@ -90,6 +101,7 @@ fmt='%-10s= %12d\n'
 printf '%-10s= %s\n' "dir" "$dir"
 printf "$fmt" "Size" "$Size"
 printf "$fmt" "Used" "$Used"
+printf "$fmt" "Avail" "$Avail"
 printf "$fmt" "minfree" "$minfree"
 printf '%-10s= %s\n' "findargs" "${findargs[*]}"
 
@@ -97,7 +109,7 @@ if [ $freeup -gt 0 ]; then
     printf "$fmt" "freeup" "$freeup"
     #TODO: declare -A links_by_inode
     cd "$dir"
-    exec 4< <(find . -mount -path ./lost+found -prune -o ! -path "./lost+found*" ! -path "." $mtimearg "${findargs[@]}" -printf '%b %i %n %y %T@ %p\0' | LC_ALL=C sort -z -k5,5 -k6r )
+    exec 4< <(find . -mount -path ./lost+found -prune -o ! -path "./lost+found*" ! -path "." ! -path "./.cleandisk.lock" $mtimearg "${findargs[@]}" -printf '%b %i %n %y %T@ %p\0' | LC_ALL=C sort -z -k5,5 -k6r )
     while read -d '' -r sz inode nlinks type mtime p <&4; do
         sz=$((sz*512))
         echo "deleting $p (type=$type, mtime='`date -d @$mtime`')"
